services:
  - type: web
    name: telegram-hedera-bot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_INVITE_LINK
        sync: false
      - key: SLOTHBAR_TOKEN_ID
        sync: false
